// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATo1D8BaF8HK1Pyo-hd7cDcYWGP85K46w',
    appId: '1:631242150485:web:be14f2e546bf15f5ecfadc',
    messagingSenderId: '631242150485',
    projectId: 'proy-final-renzo-un4',
    authDomain: 'proy-final-renzo-un4.firebaseapp.com',
    storageBucket: 'proy-final-renzo-un4.appspot.com',
    measurementId: 'G-C21CYNZ4RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-P_hxyxBtNG6f3c-xSLiTp47-8iDOgw',
    appId: '1:631242150485:android:05bb33adf30c9ae2ecfadc',
    messagingSenderId: '631242150485',
    projectId: 'proy-final-renzo-un4',
    storageBucket: 'proy-final-renzo-un4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPzXigHmBS-pLBDME5isoA1dqQeB8na4M',
    appId: '1:631242150485:ios:08aaa4414f89fa9eecfadc',
    messagingSenderId: '631242150485',
    projectId: 'proy-final-renzo-un4',
    storageBucket: 'proy-final-renzo-un4.appspot.com',
    iosClientId: '631242150485-hph7husreqpadcbhk4i8rvjs60eoprfq.apps.googleusercontent.com',
    iosBundleId: 'com.codigorenzo.proyFinalRenzo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPzXigHmBS-pLBDME5isoA1dqQeB8na4M',
    appId: '1:631242150485:ios:08aaa4414f89fa9eecfadc',
    messagingSenderId: '631242150485',
    projectId: 'proy-final-renzo-un4',
    storageBucket: 'proy-final-renzo-un4.appspot.com',
    iosClientId: '631242150485-hph7husreqpadcbhk4i8rvjs60eoprfq.apps.googleusercontent.com',
    iosBundleId: 'com.codigorenzo.proyFinalRenzo',
  );
}
